from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_CELL_VERTICAL_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

OUT=r'docs\\Guia_para_diligenciar_UXUI_EL_VITRAL_actualizada_2026-08-12.docx'
BLUE='2E74B5'; DARK='1F4D78'; LIGHT='E8EEF5'; WARN='FFF4CE'; RED='9B1C1C'

def shade(cell, color):
    tcPr=cell._tc.get_or_add_tcPr(); s=OxmlElement('w:shd'); s.set(qn('w:fill'),color); tcPr.append(s)
def cell_margin(c):
    tcPr=c._tc.get_or_add_tcPr(); m=OxmlElement('w:tcMar')
    for k in ('top','start','bottom','end'):
        n=OxmlElement('w:'+k); n.set(qn('w:w'),'100' if k in ('top','bottom') else '120'); n.set(qn('w:type'),'dxa'); m.append(n)
    tcPr.append(m)
def width(c, dxa):
    tcPr=c._tc.get_or_add_tcPr(); w=OxmlElement('w:tcW'); w.set(qn('w:w'),str(dxa)); w.set(qn('w:type'),'dxa'); tcPr.append(w)
def table(doc, heads, rows, widths=None):
    if widths is None: widths=[9360//len(heads)]*len(heads)
    t=doc.add_table(rows=1, cols=len(heads)); t.style='Table Grid'; t.alignment=WD_TABLE_ALIGNMENT.LEFT; t.autofit=False
    for i,h in enumerate(heads):
        c=t.rows[0].cells[i]; c.text=h; shade(c,LIGHT); width(c,widths[i]); cell_margin(c)
        for r in c.paragraphs[0].runs: r.bold=True; r.font.size=Pt(8.5)
    for row in rows:
        cs=t.add_row().cells
        for i,v in enumerate(row):
            cs[i].text=str(v); width(cs[i],widths[i]); cell_margin(cs[i]); cs[i].vertical_alignment=WD_CELL_VERTICAL_ALIGNMENT.CENTER
            for p in cs[i].paragraphs:
                for r in p.runs:r.font.size=Pt(8.2)
    doc.add_paragraph(); return t
def para(doc, txt='', bold=False, color=None, size=None, italic=False):
    p=doc.add_paragraph(); r=p.add_run(txt); r.bold=bold; r.italic=italic
    if color:r.font.color.rgb=RGBColor.from_string(color)
    if size:r.font.size=Pt(size)
    return p
def h(doc,txt,l=1):doc.add_heading(txt,l)
def bullets(doc,xs):
    for x in xs: doc.add_paragraph(x,style='List Bullet')
def page(doc): doc.add_page_break()
def note(doc, txt):
    t=doc.add_table(rows=1,cols=1); t.style='Table Grid'; c=t.cell(0,0); c.text='CÓMO DILIGENCIAR: '+txt; shade(c,WARN); cell_margin(c)
    for r in c.paragraphs[0].runs:r.bold=True;r.font.size=Pt(9)
    doc.add_paragraph()
def setup(doc):
    s=doc.sections[0]; s.top_margin=Inches(.75);s.bottom_margin=Inches(.75);s.left_margin=Inches(.8);s.right_margin=Inches(.8)
    st=doc.styles['Normal'];st.font.name='Calibri';st._element.rPr.rFonts.set(qn('w:ascii'),'Calibri');st._element.rPr.rFonts.set(qn('w:hAnsi'),'Calibri');st.font.size=Pt(10);st.paragraph_format.space_after=Pt(5);st.paragraph_format.line_spacing=1.1
    for name,size,color in [('Title',23,DARK),('Heading 1',15,BLUE),('Heading 2',12,BLUE),('Heading 3',11,DARK)]:
        x=doc.styles[name];x.font.name='Calibri';x.font.size=Pt(size);x.font.color.rgb=RGBColor.from_string(color);x.font.bold=True
    hp=s.header.paragraphs[0];hp.alignment=WD_ALIGN_PARAGRAPH.RIGHT; rr=hp.add_run('Guía de diligenciamiento | EL VITRAL');rr.font.size=Pt(8);rr.font.color.rgb=RGBColor(100,100,100)
    fp=s.footer.paragraphs[0];fp.alignment=WD_ALIGN_PARAGRAPH.CENTER;rr=fp.add_run('Usa esta guía junto al formato institucional original.');rr.font.size=Pt(8);rr.font.color.rgb=RGBColor(100,100,100)

doc=Document();setup(doc)
p=doc.add_paragraph();p.alignment=WD_ALIGN_PARAGRAPH.CENTER;p.paragraph_format.space_before=Pt(90);r=p.add_run('GUÍA PARA DILIGENCIAR\nDISEÑO UX/UI Y SISTEMA DE DISEÑO');r.bold=True;r.font.size=Pt(25);r.font.color.rgb=RGBColor.from_string(BLUE)
p=doc.add_paragraph();p.alignment=WD_ALIGN_PARAGRAPH.CENTER;r=p.add_run('Proyecto: Sistema digital para gestión comercial y operativa EL VITRAL');r.bold=True;r.font.size=Pt(13)
para(doc,'Esta NO reemplaza el formato SENA. Abre el PDF/Word institucional y, en cada página, copia el contenido de esta guía dentro de la tabla o sección correspondiente.',italic=True,color=RED)
note(doc,'Conservar = no borres el texto institucional. Reemplazar = cambia el ejemplo genérico por el texto indicado. Pendiente = escribir exactamente “Pendiente de validar/elaborar” hasta contar con evidencia real.')
table(doc,['Símbolo','Qué debes hacer'],[['CONSERVAR','Deja título, encabezado o explicación como viene.'],['REEMPLAZAR','Cambia la celda modelo por el texto de EL VITRAL.'],['AGREGAR','Incluye filas nuevas cuando la tabla lo permita.'],['PENDIENTE','No inventes firmas, entrevistas, resultados o aprobaciones.']], [2200,7160])
page(doc)

h(doc,'Página original 1 - Portada',1);note(doc,'REEMPLAZAR los campos vacíos de la tabla “Campo / Información”. Conserva el texto explicativo inferior.')
table(doc,['Campo del formato','Escribe exactamente'],[['Nombre del proyecto','Sistema digital para gestión comercial y operativa EL VITRAL'],['Centro de formación','PENDIENTE DE CONFIRMAR EN SOFIA Plus'],['Regional','Antioquia'],['Ficha','3144585'],['Programa','Tecnología en Análisis y Desarrollo de Software - ADSO'],['Equipo responsable','Simón Sierra López, José Manuel Ruiz Zapata y Juan José Giraldo Monsalve'],['Responsable UX/UI','Equipo EL VITRAL'],['Product Owner / cliente','Simón Sierra López (Product Owner). Agregar nombre del dueño del negocio si participa como cliente validador.'],['Instructor(es)','PENDIENTE DE CONFIRMAR: los documentos existentes mencionan a Juan Carlos Quintero Romero y Paula Andrea Bolívar Uribe.'],['Versión','1.1'],['Fecha','10/08/2026']], [2800,6560])
page(doc)

h(doc,'Página original 2 - Control documental',1);note(doc,'REEMPLAZAR “Borrador / En revisión...” por el estado actual y completar historial/aprobaciones sin inventar firmas.')
table(doc,['Elemento','Detalle para escribir'],[['Código documental','ADSO-UXUI-01'],['Nombre','Diseño UX/UI y Sistema de Diseño'],['Clasificación','Documento de diseño, validación y especificación visual'],['Estado','En revisión'],['Propietario','Equipo EL VITRAL / responsable UX/UI'],['Revisor funcional','Product Owner o dueño de EL VITRAL - PENDIENTE de confirmar'],['Revisor técnico','Equipo frontend EL VITRAL'],['Revisor académico','Instructor responsable - PENDIENTE de confirmar'],['Ubicación oficial','Repositorio EL VITRAL: /docs/diseno/ y enlace al prototipo editable cuando exista'],['Periodicidad de revisión','En cada iteración con cambios de interfaz, flujo o componente']], [2650,6710])
h(doc,'Historial de versiones',2)
table(doc,['Versión','Fecha','Descripción','Responsable','Aprobado por'],[['0.1','10/04/2026','Wireframes y mockups iniciales documentados.','Equipo EL VITRAL','Pendiente'],['1.0','PENDIENTE','Diseño aprobado para implementación.','Equipo EL VITRAL','Pendiente'],['1.1','10/08/2026','Actualización de pantallas, flujos, estados, accesibilidad y trazabilidad.','Equipo EL VITRAL','Pendiente']], [800,1150,4200,1800,1410])
h(doc,'Registro de aprobaciones',2)
table(doc,['Rol','Nombre','Decisión','Fecha','Observaciones'],[['Responsable funcional','PENDIENTE','Pendiente de aprobación','-','Validar flujos críticos.'],['Usuario representante','PENDIENTE','Pendiente de validación','-','Realizar prueba de usabilidad.'],['Líder frontend','PENDIENTE','Pendiente de revisión','-','Verificar diseño vs. código.'],['Instructor','PENDIENTE','Pendiente de revisión','-','Aprobación académica.']], [1850,1850,2050,1200,2410])
page(doc)

h(doc,'Páginas originales 3, 4 y 5 - Tabla de contenido',1);note(doc,'CONSERVAR. No copies contenido nuevo aquí. Actualiza números de página solo al finalizar el documento completo en Word.')
para(doc,'Si el documento no actualiza automáticamente la tabla de contenido: clic derecho sobre ella > “Actualizar campo” > “Actualizar toda la tabla”. No borres secciones aunque todavía estén pendientes.')
page(doc)

h(doc,'Página original 6 - 1. Propósito, alcance y principios',1);note(doc,'CONSERVAR la explicación institucional. Debajo o en la zona disponible agrega el siguiente texto para contextualizar EL VITRAL.')
h(doc,'Texto para el propósito',2)
para(doc,'El presente documento define cómo EL VITRAL comprenderá las necesidades de sus clientes y administradores, estructurará la información, diseñará y validará flujos, y aplicará reglas visuales durante la implementación. Su finalidad es digitalizar la cotización, gestión de pedidos, inventario, agenda y administración de usuarios, reduciendo ambigüedad, errores manuales y retrabajo.')
h(doc,'1.1 Objetivos específicos - conserva los de la plantilla y agrega estas precisiones',2)
bullets(doc,['Representar los flujos de registro, inicio de sesión, cotización, pedido, agenda, inventario y administración.','Documentar las 18 pantallas identificadas en el código actual.','Definir componentes reutilizables para navegación, formularios, tablas, modales, estados y mensajes.','Validar que la interfaz mantenga coherencia con los requisitos, el código y las pruebas.'])
h(doc,'1.2 Principios de diseño - reemplaza la columna “Aplicación”',2)
table(doc,['Principio','Aplicación en EL VITRAL'],[['Centrado en las personas','La cotización evita cálculos manuales y permite ingresar medidas, cantidad y producto.'],['Consistencia','Formularios, botones, tablas, colores y navegación siguen los mismos patrones.'],['Claridad','Cada pantalla debe comunicar título, acción posible, estado y resultado.'],['Accesibilidad','Se verifican etiquetas, contraste, foco y navegación por teclado.'],['Prevención de errores','Se validan campos, se confirman acciones sensibles y se exige fecha antes de entregar.'],['Diseño verificable','Cada pantalla/flujo se vincula a HU, RF, código o prueba.'],['Simplicidad responsable','No incluir pagos, facturación DIAN, contabilidad ni modo offline.']], [2350,7010])
page(doc)

h(doc,'Página original 7 - 2. Relación con otros artefactos',1);note(doc,'REEMPLAZAR el contenido de las tres columnas, pero CONSERVAR las filas y los encabezados del formato.')
table(doc,['Artefacto','Aporta','Recibe de UX/UI'],[['Formulación y alcance','Acta de constitución y DOCAL: problema de procesos manuales, usuarios, límites y objetivos.','Arquitectura de navegación, pantallas, flujos y restricciones de uso propuestas.'],['Requisitos','ELVITRAL-RF: historias, funciones, reglas, RNF y permisos.','Pantallas, flujos, componentes y criterios de usabilidad.'],['Backlog e historias','Historias de usuario y criterios de aceptación existentes en ELVITRAL-RF.','Mockups, prototipos y escenarios visuales relacionados.'],['Arquitectura','Frontend Next.js, backend Node.js, MySQL, Docker, autenticación y restricciones técnicas.','Necesidades de frontend, estados y contratos de interacción.'],['Matriz de trazabilidad','PENDIENTE DE CONSOLIDAR. Debe contener códigos HU, RF, UI, pruebas y evidencia.','UI, flujo, versión, validación y evidencia.'],['Plan de pruebas','Suite Jest y escenarios documentados en README-TEST. Plan formal pendiente de consolidar.','Casos de usabilidad, accesibilidad y compatibilidad.']], [1600,3900,3860])
page(doc)

h(doc,'Página original 8 - 3. Investigación y comprensión de usuarios',1);note(doc,'REEMPLAZAR la tabla de fuentes. Para las personas, agrega las filas siguientes. No afirmes que hubo entrevistas si no se hicieron.')
table(doc,['Fuente','Propósito','Evidencia'],[['Acta de constitución y DOCAL','Comprender problema, alcance, actores y límites.','docs/actaconstitucion.pdf y docs/DOCAL.pdf'],['ELVITRAL-RF','Identificar historias, criterios, roles y reglas.','docs/ELVITRAL-RF.pdf'],['Producto implementado','Contrastar funciones y pantallas reales.','Código frontend, backend y base de datos.'],['Suite de pruebas','Identificar validaciones y errores contemplados.','backend/__test__ y README-TEST.md'],['Entrevista / prueba con usuarios','Validar necesidades y fricciones reales.','PENDIENTE DE REALIZAR']], [1850,3300,4210])
h(doc,'3.2 Perfil o persona - agrega estas cuatro fichas',2)
table(doc,['Campo','PER-001 Cliente final'],[['Nombre del perfil','Cliente final de EL VITRAL'],['Objetivos','Cotizar productos, consultar pedidos y agendar una cita.'],['Tareas frecuentes','Ver catálogo, crear cotización, convertir cotización en pedido, ver pedidos y responder encuesta.'],['Conocimientos','Nivel digital básico/intermedio; usa lenguaje no técnico.'],['Contexto de uso','Móvil o computador; necesita respuesta rápida y clara.'],['Accesibilidad','Posibles dificultades visuales/motoras: verificar contraste, foco y tamaño táctil.'],['Frustraciones','Esperas, cálculos manuales, poca visibilidad del pedido.'],['Motivadores','Rapidez, precio estimado, seguimiento y confianza.'],['Requisitos/historias','HU-01, HU-02, HU-03; RF-001, RF-002, RF-004, RF-006.'],['Fuente','Acta, DOCAL, ELVITRAL-RF.']], [2450,6910])
page(doc)

h(doc,'Página original 9 - Investigación: perfiles y necesidades',1);note(doc,'AGREGAR las fichas de administrador, asesor e instalador. Luego completa la matriz de necesidades con estas filas.')
table(doc,['Campo','PER-002 Administrador'],[['Objetivos','Gestionar usuarios, productos, inventario, cotizaciones, pedidos y agenda.'],['Tareas frecuentes','Aprobar usuarios, crear/editar productos, registrar entradas, actualizar estados de pedido.'],['Conocimientos','Nivel digital intermedio; utiliza principalmente escritorio.'],['Contexto','Uso en oficina; requiere tablas y datos actualizados.'],['Frustraciones','Inventario visual, datos dispersos y seguimiento manual.'],['Requisitos relacionados','RF-004, RF-005, RF-006 y gestión de pedidos.'],['Fuente','DOCAL, código y esquema de base de datos.']], [2450,6910])
table(doc,['ID','Perfil','Necesidad','Problema actual','Impacto','Evidencia','Prioridad'],[['NEC-001','PER-001','Cotizar con medidas y cantidades.','Proceso manual lento y propenso a errores.','Alto','Acta/RF','Alta'],['NEC-002','PER-001','Consultar cotización y pedido.','Seguimiento no centralizado.','Alto','DOCAL','Alta'],['NEC-003','PER-002','Gestionar productos e inventario.','Control visual y pérdida de información.','Alto','Acta/DOCAL','Alta'],['NEC-004','PER-002','Organizar agenda y entregas.','Coordinación por llamadas.','Medio','DOCAL','Media'],['NEC-005','PER-002','Conocer satisfacción del cliente.','No hay registro consistente.','Medio','Acta','Media']], [850,1050,2250,2650,900,900,760])
para(doc,'PER-003 Asesor comercial y PER-004 Instalador: regístralos como perfiles definidos en DOCAL, pero con estado “no implementado como rol independiente en la versión actual”.',italic=True,color=RED)
page(doc)

h(doc,'Página original 10 - 4. Arquitectura de información y 5.1 catálogo de flujos',1);note(doc,'REEMPLAZAR las filas de ejemplo por las siguientes. Inserta el mapa del sitio como imagen o enlace editable.')
table(doc,['ID','Contenido / función','Usuario','Frecuencia','Prioridad','Ubicación','Fuente'],[['CONT-001','Inicio, proyectos y contacto','Todos','Alta','Must','/','HU-01'],['CONT-002','Catálogo y filtro por tipo','Todos','Alta','Must','/catalogo','RF catálogo'],['CONT-003','Cotización con cálculo','Autenticado','Alta','Must','/cotizar','RF-001/RF-002'],['CONT-004','Autenticación y perfil','Visitante/usuario','Alta','Must','/login, /registro, /perfil','HU-02/RF-004'],['CONT-005','Cotizaciones y pedidos','Usuario/admin','Media','Must','/cotizaciones, /mis-pedidos','RF pedidos'],['CONT-006','Administración e inventario','Admin','Alta','Must','/admin/*','RF-005'],['CONT-007','Agenda y encuesta','Usuario/admin','Media','Should','Agenda/pedidos','RF-006/RNF-003']], [700,2150,1300,1000,900,1600,1710])
table(doc,['Nivel','Elemento','Objetivo','Usuarios','Elementos hijos','Reglas de acceso'],[['1','Inicio','Explorar servicios.','Todos','Catálogo, proyectos, contacto.','Público.'],['1','Catálogo','Consultar productos.','Todos','Filtro y tarjetas.','Público.'],['1','Cuenta','Gestionar acceso.','Visitante/usuario','Login, registro, perfil.','Según sesión.'],['1','Cotizaciones y pedidos','Seguimiento comercial.','Autenticado/admin','Detalle, conversión, encuesta.','Solo propios o admin.'],['1','Administración','Operación del negocio.','Admin','Usuarios, productos, inventario, pedidos, agenda.','Rol admin.']], [550,1500,2050,1350,2250,1660])
table(doc,['ID diagrama','Nombre','Versión','Ubicación','Validado por','Fecha'],[['DIA-IA-01','Mapa general de navegación','Pendiente de elaborar','No existe todavía','No aplica','No aplica'],['DIA-IA-02','Arquitectura móvil','Pendiente de elaborar','No existe todavía','No aplica','No aplica']], [1400,2300,1500,2100,1100,960])
page(doc)

h(doc,'Página original 11 - 5. Flujos y reglas de navegación',1);note(doc,'REEMPLAZAR la tabla de catálogo y crear una ficha por flujo crítico. Copia como mínimo estas filas.')
table(doc,['ID','Nombre','Actor','Objetivo','Inicio','Fin','HU/RF','Prioridad'],[['FLU-001','Registro e inicio de sesión','Visitante','Crear cuenta e ingresar.','Registro/Login','Inicio','HU-02/RF-004','Alta'],['FLU-002','Restablecer contraseña','Visitante','Recuperar acceso.','Olvidé contraseña','Login','HU-02','Media'],['FLU-003','Crear cotización','Cliente','Generar cotización con código.','Cotizar','Confirmación','HU-03/RF-001/RF-002','Alta'],['FLU-004','Consultar/convertir cotización','Cliente/Admin','Ver detalle y crear pedido.','Cotizaciones','Pedido','RF pedidos','Alta'],['FLU-005','Consultar pedido/encuesta','Cliente','Ver pedido y calificar servicio.','Mis pedidos','Encuesta enviada','RNF-003','Media'],['FLU-006','Gestionar cita','Cliente/Admin','Crear/eliminar cita.','Agenda','Agenda actualizada','RF-006','Media'],['FLU-007','Gestionar productos/inventario','Admin','Mantener catálogo y stock.','Admin','Registro actualizado','RF-005','Alta'],['FLU-008','Gestionar pedidos','Admin','Cambiar estado y entrega.','Admin pedidos','Pedido actualizado','RF pedidos','Alta']], [700,1500,900,1800,1050,1050,1450,910])
h(doc,'Ficha para FLU-003 - Crear cotización',2)
table(doc,['Campo','Contenido que debes escribir'],[['Actor/perfil','PER-001 Cliente final autenticado.'],['Objetivo y valor','Obtener una estimación y código de cotización sin cálculos manuales.'],['Disparador','Selecciona “Cotizar” o el botón “Cotizar” desde catálogo.'],['Precondiciones','Sesión activa y productos disponibles.'],['Camino feliz','Completa datos, selecciona producto, define medidas/cantidad, agrega ítems y genera cotización.'],['Alternativas','Puede eliminar un ítem o agregar más productos antes de generar.'],['Errores y recuperación','Datos incompletos, correo inválido, lista vacía o producto inexistente; conservar datos válidos e indicar corrección.'],['Permisos','Solo usuario autenticado.'],['Pantallas','UI-002 y UI-003.'],['Criterio de éxito','Se guarda la cotización y se muestra código único.'],['Evidencia','Página /cotizar; pruebas de cotización.']], [2400,6960])
para(doc,'DÓNDE PEGARLO EN EL FORMATO ORIGINAL: esta ficha va en la tabla de la sección 5.2 “Ficha de flujo” (página original 11). Si no cabe completa, duplica esa misma tabla inmediatamente debajo y escribe como título “5.2 Ficha de flujo - continuación”.',bold=True,color=RED)
h(doc,'5.3 Reglas de navegación - tabla para copiar',2)
note(doc,'Esta tabla va en la sección 5.3, justo DEBAJO de la tabla “Ficha de flujo” de la página original 11. Reemplaza las filas NAV-001 y NAV-002 de ejemplo y agrega las otras filas.')
table(doc,['ID','Origen','Acción','Destino','Condición','Comportamiento de retorno'],[['NAV-001','UI-002 Catálogo','Seleccionar “Cotizar” en un producto','UI-003 Cotizar','Siempre; puede llevar el producto seleccionado.','Puede volver al catálogo mediante la navegación principal.'],['NAV-002','UI-003 Cotizar','Generar cotización','Confirmación en UI-003','Sesión activa, datos válidos y mínimo un producto.','Puede revisar o modificar la cotización antes de generarla.'],['NAV-003','UI-003 Cotizar','Intentar cotizar sin sesión','UI-004 Login','Usuario no autenticado.','Tras iniciar sesión, regresar a cotizar.'],['NAV-004','UI-003 Cotizar','Cerrar confirmación o consultar cotización','UI-010 Mis cotizaciones','Cotización creada correctamente.','Puede volver a cotizar o abrir sus cotizaciones.'],['NAV-005','UI-010 Mis cotizaciones','Convertir cotización en pedido','UI-011 Mis pedidos','Cotización no convertida previamente.','Puede consultar detalle del pedido creado.']], [750,1500,1600,1550,2200,1760])
para(doc,'Regla: cada fila de NAV describe una transición real entre pantallas. No necesitas inventar una por cada botón; documenta solo los cambios de pantalla o los cambios importantes de estado.',italic=True)
page(doc)

h(doc,'Página original 12 - 6. Inventario y ficha de pantallas',1);note(doc,'REEMPLAZAR las filas de ejemplo. Si la tabla no tiene espacio, continúa en la página siguiente sin borrar encabezados.')
rows=[['UI-001','Inicio','Página','Todos','Explorar servicios','HU-01','Implementado','1.1'],['UI-002','Catálogo','Página','Todos','Consultar productos','RF catálogo','Implementado','1.1'],['UI-003','Cotizar','Página','Autenticado','Crear cotización','RF-001/RF-002','Implementado','1.1'],['UI-004','Login','Página','Visitante','Iniciar sesión','HU-02','Implementado','1.1'],['UI-005','Registro','Página','Visitante','Crear cuenta','HU-02','Implementado','1.1'],['UI-006','Recuperar/restablecer contraseña','Página','Visitante','Recuperar acceso','HU-02','Implementado','1.1'],['UI-007','Sobre nosotros','Página','Todos','Conocer empresa','HU-01','Implementado','1.1'],['UI-008','Detalle de proyecto','Página','Todos','Ver proyecto','HU-01','Implementado','1.1']]
table(doc,['ID','Pantalla','Tipo','Actor','Objetivo','HU/RF','Estado','Versión'],rows,[750,1750,850,1050,2050,1350,850,710])
h(doc,'Ficha de pantalla: UI-003 Cotizar',2)
table(doc,['Campo','Contenido'],[['ID y nombre','UI-003 - Cotizar'],['Objetivo','Permitir generar cotización con medidas, cantidad y productos.'],['Usuarios / roles','Usuario autenticado.'],['Requisitos/historias','HU-03; RF-001 y RF-002.'],['Flujo','FLU-003.'],['Datos mostrados','Nombre, email, teléfono, dirección, producto, medidas, cantidad, subtotal y total.'],['Acciones','Agregar producto, eliminar producto, generar cotización.'],['Reglas/validaciones','Campos requeridos, email válido, lista no vacía y productos existentes.'],['Estados','Carga, vacío, éxito, validación, error y sesión no válida.'],['Responsive','Dos columnas en escritorio; una columna en móvil.'],['Accesibilidad','Agregar labels persistentes, foco y mensajes asociados.'],['Prototipo','MK-003 / versión 1.1 pendiente de actualizar.']], [2500,6860])
page(doc)

h(doc,'Página original 13 - Inventario de pantallas y matriz pantalla-rol-acción',1);note(doc,'AGREGAR estas filas para completar las pantallas que no estaban en el mockup inicial.')
rows=[['UI-009','Perfil/editar perfil','Página','Autenticado','Consultar/actualizar datos','HU-02','Implementado','1.1'],['UI-010','Mis cotizaciones','Página/modal','Autenticado','Consultar/convertir','RF cotizaciones','Implementado','1.1'],['UI-011','Mis pedidos/encuesta','Página/modal','Autenticado','Consultar y calificar','RF pedidos/RNF-003','Implementado','1.1'],['UI-012','Panel admin','Página','Admin','Acceder a módulos','RF-004','Implementado','1.1'],['UI-013','Admin usuarios','Página','Admin','Aprobar usuarios','RF-004','Implementado','1.1'],['UI-014','Admin productos','Página/modal','Admin','Gestionar productos','RF catálogo','Implementado','1.1'],['UI-015','Admin inventario','Página','Admin','Registrar entradas','RF-005','Implementado','1.1'],['UI-016','Admin cotizaciones','Página/modal','Admin','Consultar/convertir','RF cotizaciones','Implementado','1.1'],['UI-017','Admin pedidos','Página/modal','Admin','Gestionar estados','RF pedidos','Implementado','1.1'],['UI-018','Agenda','Widget/página','Autenticado/Admin','Gestionar citas','RF-006','Implementado','1.1']]
table(doc,['ID','Pantalla','Tipo','Actor','Objetivo','HU/RF','Estado','Versión'],rows,[750,1750,850,1050,2050,1350,850,710])
table(doc,['Pantalla','Rol','Consultar','Crear','Editar','Eliminar/desactivar','Exportar','Observaciones'],[['UI-002','Todos','Sí','No','No','No','No','Solo productos activos.'],['UI-003','Autenticado','Sí','Sí','Sí','Sí (ítem)','No','Crear cotización.'],['UI-010/UI-011','Autenticado','Sí','Pedido desde cotización','No','No','No','Solo información propia.'],['UI-013','Admin','Sí','Aprobar','Sí','Sí','No','Usuarios.'],['UI-014','Admin','Sí','Sí','Sí','Sí','No','Productos.'],['UI-015','Admin','Sí','Sí','No','No','No','Entradas inventario.'],['UI-016/UI-017','Admin','Sí','Sí','Sí','No','No','Cotizaciones/pedidos.']], [1150,950,750,850,750,1200,750,2960])
page(doc)

h(doc,'Página original 14 - 7. Wireframes y 8.1 mockups',1);note(doc,'REEMPLAZAR las filas de ejemplo. Los enlaces/ubicaciones deben apuntar a los archivos reales cuando los creen.')
table(doc,['ID','Pantalla','Objetivo','Formato','Versión','Ubicación','Estado','Validado por'],[['WF-001 a WF-016','UI-001 a UI-016 iniciales','Estructura y navegación','Media/alta','1.0.1','docs/Mockup-ELVITRAL.pdf','Documentado','Pendiente'],['WF-017','UI-015 Inventario','Documentar pantalla actual','Pendiente','1.1','docs/diseno/pantallas/','Pendiente','Pendiente'],['WF-018','UI-018 Agenda','Documentar widget/página','Pendiente','1.1','docs/diseno/pantallas/','Pendiente','Pendiente'],['WF-019','UI-006/UI-009','Contraseña y perfil editado','Pendiente','1.1','docs/diseno/pantallas/','Pendiente','Pendiente']], [1050,1600,1850,1000,850,1600,850,560])
h(doc,'7.3 Criterios de aprobación',2)
note(doc,'NO OMITIR esta tabla. Marca “Sí” solamente si cada criterio fue revisado en el wireframe correspondiente. Si no puedes demostrarlo con el mockup, escribe “No” y deja la tarea concreta en Observación; después puedes cambiarlo a “Sí” con la evidencia.')
table(doc,['Criterio','Cumple','Observación'],[
['La estructura soporta la tarea principal.','Sí','Los wireframes/documento iniciales cubren catálogo, cotización, autenticación, pedidos y administración. Validar por separado UI-006, UI-009, UI-015 y UI-018 cuando se elaboren.'],
['La jerarquía es comprensible sin decoración.','Sí','La información principal debe verse con títulos, agrupación, orden y acciones claras; comprobarlo nuevamente en cada wireframe 1.1.'],
['La navegación coincide con el flujo aprobado.','No','Aún no hay evidencia de aprobación del flujo ni prototipo navegable. Validar NAV-001 a NAV-005 y registrar aprobador/fecha.'],
['Se consideran errores y estados vacíos.','No','La sección 9 los define, pero los wireframes no demuestran todos los casos. Añadir carga, vacío, validación, error, permiso y sesión donde apliquen.'],
['No se agregan funcionalidades fuera del alcance.','Sí','Mantener fuera pagos, facturación DIAN, contabilidad y modo offline. Si se propone algo nuevo, registrarlo primero como CHG-UX.']
],[3900,1100,4360])
para(doc,'Evidencia mínima para cambiar un “No” a “Sí”: código del wireframe, versión, enlace o ubicación editable, captura, fecha de revisión y nombre de quien validó.',italic=True,color=DARK)
table(doc,['ID','Pantalla','Dispositivo','Versión','Enlace','Estado','Aprobación'],[['MK-001 a MK-016','Pantallas del mockup inicial','Escritorio y móvil','1.0.1','docs/Mockup-ELVITRAL.pdf','Documentado','Pendiente'],['MK-017 a MK-019','Inventario, agenda, recuperación/perfil','Escritorio y móvil','1.1','docs/diseno/pantallas/','Pendiente','Pendiente']], [1450,2300,1500,850,1800,850,610])
bullets(doc,['En “Criterios de aprobación” marca Sí solo después de revisar la estructura, navegación, errores/estados y alcance.','No pegues capturas sin código, fecha, versión, nombre y ubicación editable.'])
page(doc)

h(doc,'Página original 15 - 8.2 Prototipos y versionamiento',1);note(doc,'COMPLETAR el registro. Si no existe Figma u otro prototipo navegable, escribe “Pendiente de elaborar”; no pongas un enlace inexistente.')
table(doc,['ID','Flujo','Nivel','Versión','Enlace','Instrucciones','Validado por'],[['PRT-001','FLU-001 Registro e inicio','Interactivo','1.1','Pendiente de elaborar/enlazar','Probar registro, login y redirección.','Pendiente'],['PRT-002','FLU-003 Cotización','Interactivo','1.1','Pendiente de elaborar/enlazar','Crear cotización con producto, medidas y cantidad.','Pendiente'],['PRT-003','FLU-008 Pedidos admin','Interactivo','1.1','Pendiente de elaborar/enlazar','Cambiar estado y definir fecha de entrega.','Pendiente']], [950,1700,1100,800,1900,2200,710])
para(doc,'En “Reglas de versionamiento” conserva todos los puntos de la plantilla. Añade: “La versión 1.1 incorpora pantallas existentes que no estaban descritas en el mockup 1.0.1”.')
page(doc)

h(doc,'Página original 16 - 9. Estados y comportamiento',1);note(doc,'CONSERVAR la tabla de estados obligatorios. En la columna “Comportamiento esperado” puedes mantener el texto institucional. Completa la matriz y registra mensajes del proyecto.')
table(doc,['Pantalla','Inicial','Carga','Vacío','Éxito','Validación','Error','Permiso','Sesión','Observación'],[['UI-002 Catálogo','Sí','Sí','Sí','N.A.','N.A.','Sí','N.A.','N.A.','Productos activos.'],['UI-003 Cotizar','Sí','Sí','Sí','Sí','Sí','Sí','Sí','Sí','No cotiza sin sesión.'],['UI-010 Cotizaciones','Sí','Sí','Sí','Sí','N.A.','Sí','Sí','Sí','Detalle/conversión.'],['UI-011 Pedidos','Sí','Sí','Sí','Sí','Sí','Sí','Sí','Sí','Encuesta.'],['UI-014 Productos','Sí','Sí','Sí','Sí','Sí','Sí','Sí','Sí','Confirmar eliminación.'],['UI-015 Inventario','Sí','Sí','Sí','Sí','Sí','Sí','Sí','Sí','Cantidad válida.'],['UI-017 Pedidos admin','Sí','Sí','Sí','Sí','Sí','Sí','Sí','Sí','Fecha antes de entregar.'],['UI-018 Agenda','Sí','Sí','Sí','Sí','Sí','Sí','Sí','Sí','Fecha no anterior a hoy.']], [1250,550,550,550,550,750,550,650,550,3410])
bullets(doc,['No usar “Algo salió mal”. Escribir la causa y una acción: “No se pudo guardar. Intenta nuevamente”.','Conservar los datos correctos si falla un formulario.','Durante carga, evitar envíos duplicados.'])
page(doc)

h(doc,'Página original 17 - 10. Responsive y compatibilidad',1);note(doc,'REEMPLAZAR filas de ejemplo por las siguientes. Los resultados de compatibilidad quedan pendientes hasta probarlos.')
table(doc,['Perfil','Rango/dispositivo','Prioridad','Orientación','Criterio de aceptación'],[['Móvil','320-767 px','Alta','Vertical','Sin desbordamiento; controles táctiles; formularios en una columna.'],['Tableta','768-1023 px','Media','Vertical/horizontal','Grid y formularios se adaptan sin perder jerarquía.'],['Escritorio','>=1024 px','Alta','Horizontal','Tablas, paneles y navegación completa.']], [1200,1900,1050,1450,3760])
table(doc,['Componente/pantalla','Móvil','Tableta','Escritorio','Regla'],[['Navegación','Hamburguesa','Compacta','Enlaces visibles','Usar breakpoints md/lg.'],['Catálogo','1 columna','2 columnas','3 columnas','No recortar tarjetas.'],['Cotización','Columnas apiladas','Ajustable','Dos columnas','Campos legibles.'],['Tabla de datos','Scroll horizontal','Ajuste por ancho','Completa','No ocultar datos críticos.'],['Modal/panel','90% ancho y scroll','Adaptativo','Ancho de contenido','Gestionar foco.']], [1750,1700,1700,1700,2510])
table(doc,['Plataforma','Versión objetivo','Prioridad','Método de prueba','Resultado'],[['Chrome','Última estable','Alta','Manual','Pendiente de registrar'],['Edge','Última estable','Media','Manual','Pendiente de registrar'],['Firefox','Última estable','Media','Manual','Pendiente de registrar'],['Android Chrome / iOS Safari','Actual','Alta','Dispositivo o emulador','Pendiente de registrar']], [1800,1500,1100,2650,2310])
page(doc)

h(doc,'Página original 18 - 11. Accesibilidad',1);note(doc,'REEMPLAZAR “Sí / No” por el estado real de abajo. No marques Sí si no hay evidencia.')
acc=[['1','Contraste suficiente','Parcial','Paleta definida; falta medición WCAG.'],['2','Foco y orden de teclado','Pendiente','Requiere prueba manual.'],['3','Etiquetas persistentes','Parcial','Algunos campos usan placeholder.'],['4','Nombre accesible','Pendiente','Auditar iconos y botones.'],['5','No depender solo del color','Pendiente','Revisar badges/estados.'],['6','Zoom y texto legible','Pendiente','Probar zoom 200%.'],['7','Alternativa textual imágenes','Parcial','Logo/productos tienen alt; auditar resto.'],['8','Tablas comprensibles','Pendiente','Revisar thead/encabezados.'],['9','Foco en modales/menús','Pendiente','No hay evidencia de focus trap.'],['10','Errores corregibles','Parcial','Existen alertas; mejorar asociación.'],['11','Tamaño táctil','Pendiente','Probar en móvil.'],['12','Reducir movimiento','Pendiente','No hay configuración evidenciada.']]
table(doc,['N.°','Criterio','Cumple','Evidencia'],acc,[500,3200,1200,4460])
table(doc,['ID','Pantalla/componente','Criterio','Severidad','Hallazgo','Acción','Estado'],[['ACC-001','Formularios públicos','Etiquetas','Alta','Placeholder como etiqueta principal.','Añadir labels persistentes.','Abierto'],['ACC-002','Modales/menús','Foco','Alta','Sin evidencia de gestión de foco.','Implementar foco inicial, Esc y retorno.','Abierto'],['ACC-003','Badges','Color','Media','Falta validar contraste y texto.','Agregar texto/icono y medir.','Abierto'],['ACC-004','Mensajes','Errores','Media','Alertas nativas no son consistentes.','Crear alerta accesible.','Abierto']], [750,1550,950,850,2350,2050,860])
page(doc)

h(doc,'Página original 19 - Continuación de accesibilidad',1);note(doc,'No hay tabla adicional obligatoria. Usa esta página para detallar evidencias cuando realices las pruebas.')
para(doc,'Texto sugerido: “La verificación de accesibilidad se encuentra en proceso. Antes de la aprobación final se realizarán pruebas de contraste, navegación con teclado, foco en modales, zoom al 200%, etiquetas de formularios y pruebas básicas con lector de pantalla. Los hallazgos ACC-001 a ACC-004 deberán cerrarse o justificarse”.')
page(doc)

h(doc,'Página original 20 - 12. Sistema de diseño: tokens, color y tipografía',1);note(doc,'REEMPLAZAR las filas de ejemplo por estos tokens. Debes validar contraste antes de poner “Sí”.')
table(doc,['Categoría','Token','Valor','Uso','Restricción'],[['Color','color.background.primary','#101828','Fondo principal oscuro.','No usar texto oscuro sin contraste.'],['Color','color.surface','#1E2939','Tarjetas y modales.','Validar contraste.'],['Color','color.surface.secondary','#0F172A','Fondo secundario.','Uso limitado.'],['Color','color.primary.500','#3B82F6','Acción principal.','Validar contraste; consolidar token.'],['Color','color.text.primary','#FFFFFF','Texto principal.','Sobre fondos oscuros.'],['Color','color.text.secondary','#CBD5E1','Texto secundario.','No usar para información crítica sin validar.'],['Espaciado','space.4','16 px','Separación estándar.','Aplicar escala consistente.'],['Radio','radius.md','8 px recomendado','Controles y contenedores.','No mezclar radios arbitrarios.'],['Movimiento','motion.fast','150-200 ms','Transición breve.','Respetar reduced motion.']], [1300,2050,1450,2600,1960])
table(doc,['Token','Muestra/hexadecimal','Uso','Contraste validado','Observaciones'],[['color.primary.500','#3B82F6','Botones/enlaces','Pendiente','Medir contra fondo.'],['color.success.500','Verde Tailwind por consolidar','Confirmaciones','Pendiente','No depender solo de color.'],['color.warning.500','Ámbar Tailwind por consolidar','Advertencias','Pendiente','Añadir icono/texto.'],['color.error.500','Rojo Tailwind por consolidar','Errores','Pendiente','Añadir explicación.'],['color.neutral.900','#FFFFFF en tema oscuro','Texto principal','Pendiente','Revisar nomenclatura.'],['color.surface','#1E2939','Tarjetas/modales','Pendiente','Fondo oscuro.']], [1900,1900,1700,1650,2210])
page(doc)

h(doc,'Página original 21 - Tipografía, espaciado, grid y breakpoints',1);note(doc,'REEMPLAZAR las filas de la tabla de tipografía y de la tabla de grid.')
table(doc,['Token','Fuente','Peso','Tamaño/línea','Uso','Responsive'],[['font.display','Inter','700','40-48 px','Portada/hero','40 móvil; 48 escritorio.'],['font.heading.lg','Inter','700','30-36 px','Título de página','30 móvil; 36 escritorio.'],['font.heading.md','Inter','600','20-24 px','Sección','20 móvil; 24 escritorio.'],['font.body.md','Inter','400','16 px / 24 px','Texto general','Mantener legible.'],['font.label','Inter','500','14-16 px','Etiquetas','No sustituir con placeholder.'],['font.caption','Inter','400','12-14 px','Ayuda secundaria','Contraste suficiente.']], [1500,1350,700,1750,2100,1960])
table(doc,['Elemento','Escala/valor','Regla de uso'],[['Unidad base','4 px','Usar múltiplos de 4 px.'],['Contenedor','max-w-7xl; 16/24/32 px de margen','Evitar contenido pegado al borde.'],['Grid','1 columna móvil, 2 tableta, 3 escritorio','Adaptar por contenido.'],['Breakpoints','Móvil <768; md 768; lg 1024','Usar para navegación, grid y formularios.'],['Densidad','Controles con aire y área táctil suficiente','No comprimir formularios/tablas.']], [2000,2600,4760])
page(doc)

h(doc,'Página original 22 - 13. Componentes',1);note(doc,'REEMPLAZAR el catálogo y diligenciar una ficha por componente crítico. Comienza con estas filas.')
table(doc,['ID','Componente','Variantes','Estados','Uso','No usar cuando','Implementación'],[['CMP-UI-001','Navbar','Escritorio/móvil','Abierto/cerrado','Navegación y sesión','No usar como menú admin completo en móvil sin pruebas','NavBar.tsx'],['CMP-UI-002','Botón','Primario/secundario/peligro','Default, hover, focus, disabled, loading','Acciones','Etiqueta ambigua','Reutilizable'],['CMP-UI-003','Campo de texto','Texto/email/password/número/fecha','Default, focus, error, disabled','Formularios','Sin label persistente','Auth/cotización'],['CMP-UI-004','Select','Default/error','Focus, error, disabled','Producto/estado','Muchas opciones sin búsqueda','Cotización/productos'],['CMP-UI-005','Tabla','Desktop/móvil','Carga, vacío, error','Listas','Datos muy simples','Admin/pedidos'],['CMP-UI-006','Modal','Detalle/confirmación','Abierto/cerrado/error','Acciones sensibles','Sin foco/teclado','Cotizaciones/pedidos']], [1000,1500,1800,1750,1500,1750,2060])
page(doc)

h(doc,'Página original 23 - Ficha de componente y patrones funcionales',1);note(doc,'Para “Ficha de componente” usa el botón como ejemplo. Para patrones, reemplaza/añade las filas siguientes.')
table(doc,['Campo','CMP-UI-002 - Botón'],[['Propósito','Ejecutar una acción clara y visible.'],['Anatomía','Etiqueta; icono opcional; indicador de carga opcional.'],['Variantes','Primario, secundario y peligro.'],['Estados','Default, hover, focus visible, active, disabled y loading.'],['Contenido','Verbo + objeto: “Guardar cambios”, “Generar cotización”.'],['Comportamiento','Mouse, teclado Enter/Espacio y táctil.'],['Accesibilidad','Nombre accesible, foco visible, contraste y no solo color.'],['Responsive','Mantener área táctil y evitar textos cortados.'],['Tokens','color.primary.500, font.label, space.3/4, radius.md.'],['Ejemplo incorrecto','“Aceptar” cuando la acción no es clara.'],['Pruebas','Visual, teclado y disabled/loading.']], [2400,6960])
table(doc,['Patrón','Objetivo','Reglas mínimas'],[['Formulario','Capturar datos y prevenir errores.','Labels persistentes, ayuda, validación cercana y conservar datos correctos.'],['Tabla y filtros','Explorar registros.','Encabezados, carga, vacío, scroll móvil y acciones identificables.'],['Confirmación sensible','Evitar acciones accidentales.','Consecuencia clara; acción específica y cancelar.'],['Carga de archivos','No aplica en la versión actual.','Marcar N.A. hasta que exista funcionalidad.'],['Notificación','Informar resultado.','Severidad, mensaje accionable y componente accesible.']], [1850,2450,5060])
page(doc)

h(doc,'Página original 24 - 14. UX writing y 15.1 plan de prueba',1);note(doc,'CONSERVAR voz y tono de la plantilla. REEMPLAZAR la tabla de mensajes y llenar el plan de prueba con el siguiente contenido.')
table(doc,['ID','Contexto','Tipo','Mensaje','Acción'],[['MSG-001','Cotización creada','Éxito','Cotización creada correctamente. Tu código es {codigo}.','Guardar/consultar código.'],['MSG-002','Campos incompletos','Validación','Completa los campos obligatorios para continuar.','Indicar campo inválido.'],['MSG-003','Correo inválido','Validación','Ingresa un correo electrónico válido.','Corregir correo.'],['MSG-004','Sin permiso','Error seguro','No tienes permisos para realizar esta acción.','Volver/iniciar sesión.'],['MSG-005','Sin resultados','Vacío','No hay registros para mostrar todavía.','Ofrecer acción útil.'],['MSG-006','Entrega sin fecha','Validación','Define la fecha de entrega antes de marcar el pedido como entregado.','Abrir fecha.']], [800,1550,1100,4100,1810])
table(doc,['Campo','Contenido'],[['ID','USAB-001'],['Objetivo','Verificar que clientes y administrador completen flujos críticos sin ayuda mayor.'],['Hipótesis','El cliente cotiza y consulta pedido; el admin actualiza inventario y pedido.'],['Perfiles participantes','3 clientes potenciales y 1 administrador o representante autorizado.'],['Cantidad y selección','4 personas; registrar consentimiento y perfil.'],['Tareas críticas','Registro/login, cotización, pedido, agenda, producto/inventario, entrega.'],['Prototipo/versión','PRT-001 a PRT-003, versión 1.1 cuando estén disponibles.'],['Modalidad','Moderada, presencial o remota.'],['Métricas','Éxito, tiempo, errores, satisfacción y comentarios.'],['Criterio de aprobación','80% completa cada tarea crítica sin ayuda mayor.'],['Responsable/fecha','Equipo EL VITRAL / PENDIENTE de programar.']], [2400,6960])
page(doc)

h(doc,'Página original 25 - Guion, resultados y hallazgos de usabilidad',1);note(doc,'La tabla de tareas sí puedes llenarla ya. La de resultados/hallazgos debe quedar “Pendiente” hasta ejecutar la prueba.')
table(doc,['ID','Escenario','Tarea','Éxito esperado','Dato a observar'],[['TAR-USAB-01','Cliente nuevo','Registrarse e iniciar sesión.','Accede a cuenta.','Errores y comprensión.'],['TAR-USAB-02','Cliente','Crear cotización con medidas.','Obtiene código.','Tiempo/campos dudosos.'],['TAR-USAB-03','Cliente','Consultar pedido y encuesta.','Ve detalle y envía respuesta.','Comprensión de estados.'],['TAR-USAB-04','Admin','Crear producto y registrar entrada.','Producto/entrada visibles.','Navegación/validaciones.'],['TAR-USAB-05','Admin','Cambiar pedido a entregado.','Define fecha y confirma.','Comprensión de regla.']], [1150,1600,2550,2300,1760])
table(doc,['Participante','Tarea','Completó','Tiempo','Errores','Hallazgo','Severidad'],[['P-01','TAR-USAB-01','Pendiente','-','-','Pendiente de prueba','-'],['P-02','TAR-USAB-02','Pendiente','-','-','Pendiente de prueba','-'],['P-03','TAR-USAB-03','Pendiente','-','-','Pendiente de prueba','-'],['P-04','TAR-USAB-04/TAR-USAB-05','Pendiente','-','-','Pendiente de prueba','-']], [1200,1550,1050,850,900,2500,1310])
table(doc,['ID','Hallazgo','Evidencia','Severidad','Decisión','Responsable','Estado'],[['UXH-001','Pendiente de registrar','Notas/video','-','-','-','Pendiente'],['UXH-002','Pendiente de registrar','Notas/video','-','-','-','Pendiente']], [900,2450,1600,1100,1350,1200,760])
page(doc)

h(doc,'Página original 26 - 16. Handoff, decisiones y cambios',1);note(doc,'REEMPLAZAR las celdas de ubicación/responsable/verificación. Agrega las decisiones ya tomadas y registra cambios futuros.')
table(doc,['Elemento','Obligatorio','Ubicación','Responsable','Verificación'],[['Prototipo versionado','Sí','docs/diseno/ o Figma','Equipo UX/UI','Pendiente de enlace'],['Inventario de pantallas','Sí','Sección 6 / docs/diseno/','Equipo UX/UI','UI-001 a UI-018'],['Tokens y estilos','Sí','Sección 12','Frontend/UX','Consolidar primary'],['Componentes y estados','Sí','Secciones 9 y 13','Frontend/UX','Auditoría pendiente'],['Assets exportables','Según aplique','frontend/public y docs/diseno/assets','Equipo','Verificar origen/licencia'],['Reglas responsive','Sí','Sección 10','Frontend','Probar dispositivos'],['Accesibilidad','Sí','Sección 11','Frontend/UX','Cerrar ACC abiertos'],['Mensajes/contenido','Sí','Sección 14','UX/UI','Migrar alertas nativas'],['Trazabilidad UI-HU-RF','Sí','Sección 17','Equipo','Actualizar versión'],['Hallazgos pendientes','Sí','Secciones 11/15','Equipo','Revisar antes entrega']], [2100,1050,2400,1600,2210])
table(doc,['ID','Fecha','Contexto','Alternativas','Decisión','Justificación','Impacto','Responsable'],[['DD-001','10/04/2026','Alcance','Web/app nativa','Web responsive','Recursos y alcance.','Breakpoints','Equipo'],['DD-002','10/04/2026','Roles','Varios roles/dos roles','Usuario y admin','Roles reales de BD.','Asesor/instalador pendientes','Equipo'],['DD-003','10/04/2026','Funciones','Incluir/no incluir pagos','Excluir pagos/facturación','Fuera del MVP.','No crear pantallas pago','Equipo'],['DD-004','10/08/2026','Documentación','16/18 pantallas','Documentar UI-001 a UI-018','Código tiene más vistas.','Actualizar mockups','Equipo']], [700,1000,1350,1300,1450,1500,1260,800])
h(doc,'16.3 Solicitud de cambio de diseño',2)
note(doc,'REEMPLAZAR las filas modelo. Registra un cambio solo cuando modifica una pantalla, flujo, componente, contenido, regla o alcance. Si todavía no hay aprobación formal, escribe “Pendiente de aprobación”; no marques Aprobado/Rechazado sin evidencia.')
table(doc,['ID','Origen','Cambio solicitado','Motivo','Impacto','Decisión','Versión','Responsable'],[
['CHG-UX-001','Auditoría UX/UI del 12/08/2026','Actualizar wireframes/mockups de UI-006, UI-009, UI-015 y UI-018; enlazar la versión editable.','El código contiene estas vistas, pero el mockup 1.0.1 no las documenta completamente.','Actualiza secciones 6, 7, 8, 16 y 17; requiere revisión de flujos y responsive.','Pendiente de aprobación','1.1','Equipo UX/UI'],
['CHG-UX-002','Auditoría UX/UI del 12/08/2026','Reemplazar alert() y confirm() nativos por mensajes y confirmaciones reutilizables y accesibles.','Hay mensajes dispersos, sin consistencia visual ni evidencia completa de teclado/foco.','Afecta productos, agenda, pedidos, cotizaciones, sección 9, sección 13 y pruebas de accesibilidad.','Pendiente de aprobación','1.1','Frontend/UX']
],[950,1250,2250,2000,2200,1450,750,510])
para(doc,'Al aprobar una solicitud: conserva el mismo ID, cambia “Decisión” por Aprobado o Rechazado, registra fecha y evidencia en observación o en el registro de decisiones. Si se implementa, actualiza también la versión del mockup, pantalla y matriz de trazabilidad.',italic=True,color=DARK)
page(doc)

h(doc,'Página original 27 - 17. Trazabilidad, indicadores y checklist',1);note(doc,'REEMPLAZAR la matriz con estas filas. En el checklist marca “Parcial” o “Pendiente” hasta tener evidencia.')
table(doc,['UI/flujo','Perfil','HU/CU','RF/RNF','Reglas','Componente','Prueba','Evidencia','Estado'],[['UI-001/UI-002','Todos','HU-01','RF catálogo','Productos activos','Navbar/cards','Catálogo','Mockup/código','Implementado'],['UI-003/FLU-003','Cliente','HU-03','RF-001/RF-002','Datos válidos','Formulario/select','Cotización','Código/tests','Implementado'],['UI-004/UI-005','Visitante','HU-02','RF-004','Credenciales','Inputs/captcha','Login/registro','Código/tests','Implementado'],['UI-010/UI-011','Cliente','Pedidos','RNF-003','Solo propios','Tabla/modal','Pedidos','Código/tests','Implementado'],['UI-014/UI-015','Admin','Inventario','RF-005','Rol admin','Tabla/formulario','Productos/inventario','Código/tests','Implementado'],['UI-017/FLU-008','Admin','Pedidos','RF pedidos','Fecha entrega','Tabla/modal','Pedidos','Código/tests','Implementado'],['UI-018/FLU-006','Cliente/Admin','Agenda','RF-006','Fecha válida','Agenda','Pendiente UX','Código','Implementado']], [1150,800,900,1050,1200,1200,1050,1200,810])
table(doc,['Indicador','Fórmula/método','Meta','Frecuencia','Fuente'],[['Cobertura pantallas','Pantallas trazadas / inventariadas','100%','Por versión','Matriz UI'],['Flujos críticos validados','Flujos aprobados / críticos','100% antes entrega','Por iteración','Pruebas UX'],['Éxito de tareas','Participantes que completan / total','>=80%','Por prueba','Resultados USAB'],['Hallazgos críticos abiertos','Conteo','0 antes de entrega','Semanal','Registro UX'],['Cobertura de estados','Estados diseñados / aplicables','100%','Por versión','Ficha UI'],['Componentes reutilizados','Uso componentes / total aplicable','Definir línea base','Por release','Código/diseño']], [1900,2600,1500,1500,1860])
page(doc)

h(doc,'Página original 28 - Checklist final y aprobación',1);note(doc,'La respuesta correcta hoy NO es “Sí” para todo. Usa el estado indicado hasta conseguir evidencia.')
checks=[['1','Perfiles/necesidades tienen fuente o validación.','Parcial','Fuentes documentales; falta validación directa.'],['2','Arquitectura coincide con alcance.','Sí','Mapa documentado; validar visualmente.'],['3','Flujos principales, alternativos y errores documentados.','Parcial','Faltan diagramas detallados de todos.'],['4','Pantallas tienen código y trazabilidad.','Sí','UI-001 a UI-018 inventariadas.'],['5','Prototipos versionados y aprobados.','Parcial','Mockup 1.0.1; faltan actualizaciones/aprobación.'],['6','Estados definidos.','Sí','Sección 9.'],['7','Responsive especificado.','Sí','Sección 10; falta prueba completa.'],['8','Accesibilidad verificada.','Pendiente','Hallazgos ACC abiertos.'],['9','Sistema diseño con tokens/componentes.','Parcial','Documentado; consolidar token primary.'],['10','Textos consistentes/accionables.','Parcial','Catálogo inicial; mejorar alertas.'],['11','Pruebas de usabilidad o justificación.','Pendiente','Plan creado; prueba sin ejecutar.'],['12','Handoff sin ambigüedad.','Parcial','Faltan prototipos finales.'],['13','Interfaz corresponde versión aprobada.','Pendiente','Esperar aprobación.'],['14','Cambios posteriores registrados.','Sí','Sección 16.']]
table(doc,['N.°','Verificación','Cumple','Evidencia/observación'],checks,[500,3850,1200,3810])
table(doc,['Rol','Nombre','Decisión','Fecha','Firma/evidencia'],[['Responsable funcional','PENDIENTE','Pendiente','-','-'],['Usuario representante','PENDIENTE','Pendiente','-','-'],['Líder frontend','PENDIENTE','Pendiente','-','-'],['Instructor','PENDIENTE','Pendiente','-','-']], [2000,2300,1800,1400,1860])
page(doc)

h(doc,'Página original 29 - Anexos A, B y C',1);note(doc,'CONSERVAR el Anexo A de prefijos. En el Anexo B usa la estructura siguiente; en el C marca el nivel actual con honestidad.')
para(doc,'Anexo A: no cambies los prefijos PER, NEC, CONT, FLU, NAV, UI, WF, MK, PRT, CMP-UI, MSG, USAB, UXH, DD y CHG-UX.')
para(doc,'Anexo B - estructura a crear en el repositorio:')
para(doc,'/docs/diseno/\n  investigacion/\n  arquitectura-informacion/\n  flujos/\n  pantallas/\n  sistema-diseno/\n  pruebas-usabilidad/\n  decisiones/\n  assets/\n  README.md')
table(doc,['Nivel','Estado actual para EL VITRAL','Qué falta para marcarlo completo'],[['Formulación','Parcial','Perfiles preliminares, mapa de sitio y wireframes críticos.'],['Construcción inicial','Parcial','Mockups de UI-015, UI-018, UI-006/UI-009 y validación.'],['Producto funcional','Parcial','Prototipo navegable, accesibilidad básica y prueba de usabilidad.'],['Producto profesional','Pendiente','Biblioteca, pruebas visuales, auditoría a11y y control versiones.'],['Producto avanzado','No aplica por ahora','Analítica, experimentación y automatización visual.']], [2100,2250,5010])
page(doc)

h(doc,'Página original 30 - Anexo D y cierre',1);note(doc,'CONSERVAR los errores frecuentes de la plantilla. Añade los pendientes reales del proyecto como evidencia de control.')
table(doc,['Pendiente real','Qué debes hacer'],[['Datos institucionales','Confirmar centro de formación, regional, instructor y aprobadores.'],['Mockups faltantes','Crear/actualizar UI-006, UI-009, UI-015 y UI-018.'],['Prueba de usabilidad','Ejecutar USAB-001 y llenar resultados/hallazgos.'],['Accesibilidad','Resolver ACC-001 a ACC-004 y realizar verificación.'],['Design tokens','Definir de forma centralizada color.primary.500.'],['Mensajes','Reemplazar alert()/confirm() nativos por mensajes y modales consistentes/accesibles.'],['Compatibilidad','Probar Chrome, Edge, Firefox, Android y Safari/iOS.'],['Aprobaciones','Completar solo al final con evidencia real.']], [2500,6860])
para(doc,'Cierre para conservar/adaptar: “El documento se considerará completo cuando una persona externa pueda entender los usuarios, recorrer los flujos, localizar las pantallas, implementar los componentes y verificar la experiencia sin depender de explicaciones informales.”',italic=True)
para(doc,'Fuentes usadas para esta guía: formato SENA de 30 páginas, Acta de constitución, DOCAL, ELVITRAL-RF, Mockup-ELVITRAL, código frontend/backend, esquema de base de datos y README-TEST del repositorio.',italic=True,color=DARK)
page(doc)
h(doc,'Anexo E - Actualización de auditoría del proyecto (12/08/2026)',1)
note(doc,'AGREGAR este anexo al final del formato institucional o usarlo como lista de control antes de entregar. Los hallazgos provienen de la revisión del repositorio; no sustituyen pruebas con usuarios ni pruebas en dispositivos reales.')
para(doc,'Resumen honesto: la base funcional está avanzada (catálogo, autenticación, cotización, pedidos, administración, inventario y agenda), pero la evidencia UX/UI todavía es parcial. El mayor riesgo de entrega no es que falten funciones: es que falten prototipos actualizados, validación de accesibilidad, pruebas de usabilidad y un sistema de diseño aplicado de forma centralizada.',bold=True,color=DARK)
h(doc,'Correcciones de inventario y trazabilidad',2)
table(doc,['Hallazgo','Evidencia revisada','Qué debes dejar en el documento'],[
['INV-001','Hay 20 archivos page.tsx en frontend/app. El inventario usa 18 IDs porque UI-006 agrupa olvide/reset password y UI-009 agrupa perfil/editar perfil.','Mantener UI-001 a UI-018, pero agregar nota de agrupación y trazar las rutas /olvide-password, /reset-password/[token], /perfil y /perfil/editar por separado.'],
['INV-002','Existen vistas públicas adicionales: sobre nosotros y detalle de proyecto; ya corresponden a UI-007 y UI-008.','En cada ficha UI registrar ruta exacta, estado, captura o enlace editable y responsable de validación.'],
['INV-003','La agenda aparece como widget público y también como pantalla administrativa.','Separar en la ficha UI-018 los dos contextos, permisos y acciones de cliente/admin; no documentarlos como una sola pantalla sin aclaración.'],
['TRZ-001','La matriz cita HU/RF, pero no existe una matriz consolidada UI-ruta-HU-RF-prueba-evidencia en docs/diseno/.','Crear la matriz como archivo versionado y enlazarla desde la sección 17.']
],[1700,3800,3860])
h(doc,'Pendientes UX/UI priorizados',2)
table(doc,['ID','Prioridad','Hallazgo verificable','Acción y criterio de cierre'],[
['ACC-005','Alta','Solo hay una aparición de atributos aria- en los componentes TSX revisados; varios modales tienen cierre con × sin nombre accesible.','Agregar aria-label a los cierres, foco inicial, Escape, retorno de foco y probar flujo completo solo con teclado. Adjuntar evidencia.'],
['UX-005','Alta','Se identificaron 25 usos de alert() o confirm() en frontend. Esto rompe consistencia visual y no asegura mensajes asociados al campo.','Definir Toast/AlertDialog reutilizable; reemplazar alert/confirm en productos, agenda, pedidos y cotizaciones. Cerrar cuando error, éxito y confirmación se lean y operen con teclado.'],
['DS-005','Alta','La guía define color.primary.500 e Inter, pero globals.css usa Arial y variables Geist; no hay un token primary central visible.','Alinear documento y código: definir tokens CSS/Tailwind, fuente real, colores, focus ring y estados. No declarar tokens como implementados hasta comprobarlos.'],
['TEST-UX-001','Alta','Hay 10 archivos de prueba backend; README-TEST declara pruebas comentadas y ausencia de E2E. No hay evidencia de pruebas visuales, accesibilidad o responsive.','Ejecutar USAB-001, registrar resultados, crear al menos un recorrido E2E de registro-cotización-pedido y una lista de prueba a11y/responsive.'],
['SEC-UX-001','Alta','middleware.ts decodifica el JWT antes de verificarlo y registra el token/contenido en consola.','Solicitar revisión técnica: verificar token antes de confiar en el rol y eliminar registros de token. Documentar la decisión en handoff; es un riesgo de seguridad que afecta permisos y confianza.'],
['RSP-005','Media','La guía contiene breakpoints, pero no hay resultados registrados para Chrome, Edge, Firefox, Android Chrome ni Safari iOS.','Tomar capturas de las 6 pantallas/flujos críticos en 320, 768 y 1024 px; registrar defectos, navegador y fecha.'],
['A11Y-IMG-001','Media','Se usan imágenes nativas y las alternativas de texto requieren auditoría, especialmente cuando la imagen provenga de producto.','Revisar alt informativo/decorativo y reemplazar img por el componente de imagen del framework cuando aplique; adjuntar resultado de auditoría.']
],[950,850,3450,4110])
h(doc,'Orden recomendado para cerrar la entrega',2)
bullets(doc,['1. Corregir los puntos de alta prioridad: ACC-005, UX-005, DS-005, TEST-UX-001 y SEC-UX-001.','2. Crear o actualizar mockups/wireframes de UI-006, UI-009, UI-015 y UI-018 y enlazarlos con rutas reales.','3. Ejecutar la prueba de usabilidad con 4 participantes y no modificar los resultados antes de contar con evidencia.','4. Probar responsive y accesibilidad; cerrar cada ACC con captura, fecha, responsable y resultado.','5. Actualizar la matriz de trazabilidad y solo entonces diligenciar aprobaciones y tabla de contenido final.'])
para(doc,'Corrección de portada: el formato institucional indica SENA Pedregal, Juan Carlos Quintero y fecha 10/08/2026. Confirma estos datos en SOFIA Plus; solo agrega a Paula Andrea Bolívar Uribe si corresponde oficialmente.',italic=True,color=DARK)
para(doc,'Estado global sugerido para la entrega actual: Producto funcional = Parcial/avanzado; documentación UX/UI y sistema de diseño = Parcial. No usar “aprobado” hasta completar los cierres de este anexo y contar con evidencia.',bold=True,color=RED)
doc.save(OUT); print(OUT)
